#!/usr/bin/python
# -*- coding: utf-8 -*-

# define feed source

CONSTANT_FEED_FROM_WEB = 1
CONSTANT_FEED_FROM_ANDROID = 2
CONSTANT_FEED_FROM_IPHONE = 3

# define feed type

CONSTANT_FEED_TYPE_COMMENT = 2001
CONSTANT_FEED_TYPE_BUY = 2002

# define order status

CONSTANT_ORDER_STATUS_INIT = 0
CONSTANT_ORDER_STATUS_NEW = 1
CONSTANT_ORDER_STATUS_LOCKED = 3
CONSTANT_ORDER_STATUS_COMFIRMED = 5
CONSTANT_ORDER_STATUS_PAID = 7
CONSTANT_ORDER_STATUS_FINISHED = 9
CONSTANT_ORDER_STATUS_DISCARD = 11

# define compartment requirement

CONSTANT_ORDER_ROOM_PRIORITY = 1
CONSTANT_ORDER_HALL_PRIORITY = 2
CONSTANT_ORDER_ROOM_ONLY = 3
CONSTANT_ORDER_HALL_ONLY = 4

# define gender constant

CONSTANT_GENDER_MR = 1
CONSTANT_GENDER_MS = 2
CONSTANT_GENDER_COMPANY = 3

